### ISSUE TITLE
1주차 질문

### ISSUE THREAD

**Issue by sypark9646** [back-end-stduy-doldol/Study#3]
- tcp와 virtual circuit의 관계가 있는가? 터널기법 키워드로 알아보기
- Http 내 커넥션 관리가 end-to-end인지 hop-by-hop인지 s3 일 때는? (ipv6의 경우 hop-by-hop이다)(?)

**Comment by jordy-torvalds** [comment]
# 아파치 vs 엔직엑스 질문
1. 요청이 엔진엑스의 이벤트 큐에 적재 되면 바로 리스폰스롤 보내고, 진짜 응답은 콜백으로 주는건가요?
2. 동기식으로 짜진 어플리케이션을 와스로 하고 비동기식인 엔진엑스와 리버스 프록시로 통신하며 서비스한다고 했을 때 통신 방식 불일치(?)로 인한 오작동 같은 것은 없나요?
3.  nginx가 비동기식이다 보니 많은 요청에 대응하기 좋다고하는데 결국 하나의 event queue에 너무 많은 요청이 적재가 되면 성능이 저하되지 않는지 궁금합니다 (계준님 질문 + 제 질문)

**Comment by jordy-torvalds** [comment]
### HTTP3 QUIC 질문
- QUIC 신뢰성 있는 루트 CA 를 통해 인증된 TSL 인증서가 적용되어 있어야만 사용가능한 프로토콜인것인지,
QUIC자체가 TLS를 제공해주는 것인지

**Comment by woo-yu** [comment]
Apache vs Nginx 질문
nginx는 싱글 스레드로 worker가 처리하면 i/o는 어떻게 처리하나요?

**Comment by woo-yu** [comment]
@jordy-torvalds 
#### Q. QUIC 신뢰성 있는 루트 CA 를 통해 인증된 TSL 인증서가 적용되어 있어야만 사용가능한 프로토콜인것인지, QUIC자체가 TLS를 제공해주는 것인지
---
**A.** QUIC에서는 기본적으로 TLS를 적용하고 (https://blog.cloudflare.com/the-road-to-quic/),
HTTP2에서는 TLS가 필수는 아니지만 브라우저에서 HTTP2에 TLS를 적용해야 사용 가능하게끔 한다고 하네요!(https://http2.github.io/faq/)  *정확히는 TLS와 같은 보안을 적용해야 HTTP2를 사용가능하게함*

**Comment by midaslmg94** [comment]
@jordy-torvalds 
**Q1. 요청이 엔진엑스의 이벤트 큐에 적재 되면 바로 리스폰스를 보내고, 진짜 응답은 콜백으로 주는건가요?**

A1. 응답을 콜백으로 준다는 말씀이 nonblocking 방식에서 request에 대한 response가 콜백으로 보내냐는 질문이시라면, 2번의 답변과 비슷하다고 생각합니다. (제가 2번에 대한 답변을 먼저 적어서요 ㅎㅎ)

- 동기, 비동기, 블로킹, 논블로킹에 대한 설명은 [[10분 테코톡] 🎧 우의 Block vs Non-Block & Sync vs Async](https://www.youtube.com/watch?v=IdpkfygWIMk&list=PLgXGHBqgT2TvpJ_p9L_yZKPifgdBOzdVH&index=32)의 7분 30초 ~ 10분 30초를 참고해주세요
- [7주차-blocking & non-blocking](https://www.slipp.net/wiki/pages/viewpage.action?pageId=19530144&preview=%252F19530144%252F20742359%252Ftagcloud.png)

---
**Q2. 동기식으로 짜진 어플리케이션을 와스로 하고 비동기식인 엔진엑스와 리버스 프록시로 통신하며 서비스한다고 했을 때 통신 방식 불일치(?)로 인한 오작동 같은 것은 없나요?**

A2. 문제는 없을것 같습니다. nginx의 역할은 앞단(클라이언트)에서 받은 요청을 뒷단(WAS)로 넘겨주고 WAS의 리스폰스를 다시 클라이언트로 돌려주는 것인데, nginx가 넘겨준 request를 처리하는 것은 서버의 몫이므로 nginx는 서버에게 넘긴 요청에 대한 응답만 받아서 클라이언트에게 돌려주면 될 것 같습니다.


---
**Q3. nginx가 비동기식이다 보니 많은 요청에 대응하기 좋다고하는데 결국 하나의 event queue에 너무 많은 요청이 적재가 되면 성능이 저하되지 않는지 궁금합니다 (계준님 질문 + 제 질문) @Kyejoon-Lee** 

 A3. 해당 문제는 nginx에서 성능 저하를 일으키는 원인이었다고 합니다. *따라서 nginx 1.7.11 버전 이후에는 스레드 풀*(Thread Pool)을 사용해서 문제를 해결했다고 합니다. 

> Event Loop가 동작하는 Main Thread에서는 Event를 직접처리 하거나, Event를 Event Queue에 넣는다. Event Queue에 들어간 Event는 Thread Pool의 Worker Thread들이 하나씩 가저가 처리하고, 처리가 완료되면 Main Loop에게 Event 처리 완료 메세지를 보낸다. 이러한 Thread Pool 기법에서는 하나의 Worker Thread가 Event 처리로 Blocking 되어도 나머지 Worker Thread에게는 영향을 주지 않기 때문에 Blocking 문제를 해결할 수 있다. 현재 Nginx는 File Read/Write 동작만 Thread Pool의 Thread에서 처리하고, 나머지 Event들은 기존 그대로 Main Thread에서 처리하고 있다.

- [Thread Pools in NGINX Boost Performance 9x!](https://www.nginx.com/blog/thread-pools-boost-performance-9x/
)
- [Nginx Thread Pool](https://ssup2.github.io/theory_analysis/Nginx_Thread_Pool/)

**Comment by sypark9646** [comment]
@Kyejoon-Lee 
**Q1. tcp와 virtual circuit의 관계가 있는가?**

* [Does TCP use virtual circuit model?](https://networkengineering.stackexchange.com/questions/6307/does-tcp-use-virtual-circuit-model)
이 질문에 대해서는 저도 좀 헷갈리긴 하는데, tcp 공식문서 자체에서는 virtual circuit에 대한 내용이 없기도 해서 말씀하신대로 tcp 자체와 virtual circuit는 관계가 없는 것이 맞는 것 같습니다. 

* [Internet Core Protocols: The Definitive Guide by Eric Hall](https://www.oreilly.com/library/view/internet-core-protocols/1565925726/ch07s01s03.html)
![image](https://user-images.githubusercontent.com/46469385/107344749-25051d00-6b06-11eb-9a36-da4bab158d80.png)
여기 보시면 `TCP는 IP의 패킷 중심 네트워크 계층 위에 가상 회로를 구축 한 다음 가상 회로를 통해 전송되는 데이터를 추적한다`는 내용과  `두 TCP 끝점 사이에 연결이 이루어질 때마다 모든 데이터가 가상 회로를 통해 전달됩니다`라고 하는데, TCP의 특징은 아니지만, TCP가 virtual circuit을 사용한다 정로도 이해하면 될 것 같습니다
- - -
**Q2. Http 내 커넥션 관리가 end-to-end인지 hop-by-hop인지?**

* https://developers.google.com/web/fundamentals/performance/http2
`흐름 제어는 종단간(End-to-End) 방식이 아니라 홉(Hop-by-Hop) 방식입니다. 즉, 중개자가 자체적인 기준과 추론에 따라 리소스 사용을 제어하고 리소스 할당 메커니즘을 구현할 수 있습니다.`

* https://developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x
 `HTTP 내 커넥션 관리가 end-to-end가 아닌 hop-by-hop인 두 개의 연속된 노드 사이의 커넥션에 적용된다는 것입니다. 클라이언트와 첫 번째 프록시 사이의 커넥션 모델은 프록시와 최종 목적 서버(혹은 중간 프록시들) 간의 것과는 다를 수도 있습니다. Connection와 Keep-Alive와 같이 커넥션 모델을 정의하는 데 관여하는 HTTP 헤더들은 hop-by-hop 헤더이며, 중간 노드에 의해 그 값들이 변경될 수 있습니다.`
