### ISSUE TITLE
3주차 질문

### ISSUE THREAD

**Issue by midaslmg94** [back-end-stduy-doldol/Study#5]
3주차 질문 내용 정리

**Comment by doorisopen** [comment]
Q1. 쿠키의 단점이 보안이 좋지 않다는 점인데, 이 단점을 헤더 설정 등으로 보완해서 전송한다면 어떨까?(준님)

Q2. 레디스를 사용하는 이유?(돌돌님)

Q3. 세션은 세션 스토리지에 안담기나요?(슭슭님)

Q4. jwt는 http only같은걸 못붙이나요?(슭슭님)

**Comment by doorisopen** [comment]
Q2. 레디스를 사용하는 이유?( @midaslmg94  )

* [참고 링크](https://medium.com/@jyejye9201/%EB%A0%88%EB%94%94%EC%8A%A4-redis-%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80-2b7af75fa818)

**Comment by doorisopen** [comment]
Q3. 세션은 세션 스토리지에 안담기나요?( @HJ-Woo )

간단하게 로컬 스토리지와 세션 스토리지에 대해서 조사하였는데

* **HTML5에서 추가된 key-value 형태의 저장소**
* 서버에 데이터를 저장하지 않는다.
* 용량이 크다(5MB, 브라우저마다 차이 있음)
  + 쿠키는 약 4kb 용량 
* HTML5를 지원하는 브라우저에서만 사용가능하다.
* 클라이언트의 정보를 저장한다.
* 쿠키의 단점을 보완한 저장소
* 로컬 스토리지와 세션 스토리지의 차이점은 **데이터 영구성의 차이**
  + 로컬 스토리지: 사용자가 정보를 지우지 않는 이상 계속 브라우저에 남아있음
  + 세션 스토리지: 브라우저 탭을 닫을 경우 제거됨
* 비밀번호같은 중요한 정보는 저장하지 안됩니다.(탈취의 위험이 있음)

반면 쿠키는,
* 대부분의 브라우저에서 지원합니다.
* HTTP 요청마다 포함되고, API 호출로 서버에 부담(4kb 용량의 쿠키가 매번 호출되는 상황을 생각하시면 될듯합니다.)
* 쿠키는 약 4kb 용량
* 암호화 되지 않아 사용자 정보 도난의 위험이 있음

그럼 쿠키, 로컬, 세션 스토리지의 **사용예시**는?
* 로컬 스토리지: 자동 로그인
* 세션 스토리지: 입력 폼 정보 유지, 비로그인 장바구니
* 쿠키: 팝업창 24시간동안 보지않기

### 결론
로컬, 세션 저장소는 쿠키의 단점을 보완해서 나온 기술이기 때문에 **세션 정보를 세션 저장소에 담을수 있습니다.**

그러나, 다음 사항들을 참고해 주세요

* 쿠키와 동일하게 클라이언트 사이드에 저장되므로 중요한 정보를 담아선안된다.
* 쿠키와 달리 서버로 값을 전송하지 않아서, 서버의 부하를 줄일 수 있다.
* **세션 스토리지의 경우**, 브라우저 Tab마다 개별적으로 저장되기 때문에 세션 스토리지를 이용해 로그인을 구현한다면 동일 사이트 Tab1(로그인 yes), Tab2(로그인 no)인 상태를 볼 수 있습니다.
  + **도메인 별로 로그인을 유지하고 싶다면, 로컬 스토리지에 저장**하면됩니다. 그러나, 로컬 스토리지의 특징을 보면 사용자가 데이터를 지우지 않으면 반영구적으로 저장되기 때문에 로그인이 풀리지 않음을 주의해야합니다. 

### References
* [로컬스토리지, 세션스토리지, 쿠키 정리](https://velog.io/@kler/TIL4-%EB%A1%9C%EC%BB%AC%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80-%EC%84%B8%EC%85%98%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80-%EC%BF%A0%ED%82%A4-%EC%A0%95%EB%A6%AC)
* [로컬스토리지, 세션스토리지](https://www.zerocho.com/category/HTML&DOM/post/5918515b1ed39f00182d3048)
* [Session storage : 세션 스토리지 정리](https://developingbear.tistory.com/140)
* [쿠키, 세션, 로컬 스토리지, 세션스토리지, indexedDB, 캐시](https://tristan91.tistory.com/521)

**Comment by doorisopen** [comment]
Q4. jwt는 http only같은걸 못붙이나요? ( @HJ-Woo )

우선 답변은 토큰은 http only 속성을 활성화하는 방법은 없는것 같습니다.

토큰을 저장, 관리하는 측면에서 보면 

* 웹 스토리지(로컬, 세션 스토리지)
* 쿠키

위 2가지를 볼 수 있는데,

토큰(jwt)을 쿠키에 저장하는 경우에, XSS 취약점을 막기 위해서 httpOnly 속성을 활성화하고 set-cookie로 지정해준 쿠키에 토큰을 담아서 서버에 전송한다는 내용 위주로 있는 것으로 보아 토큰 자체에서 httpOnly 속성을 활성화 하는 방법은 없지 않나 싶습니다 ㅎ..

### References
* [JWT 이해 및 적용](https://backend-intro.vlpt.us/4/)
* [JWT, Cookie, XSS, CSRF](https://mygumi.tistory.com/375)
* [JSON 웹 토큰은 어디에 저장해야합니까?](https://ichi.pro/ko/ban-eung-injeung-kukie-jwtleul-jeojanghaneun-bangbeob-57608818986625)
* [안전한-jwt-웹서비스-사용자-인증-구현하기](https://diokun.wordpress.com/2017/04/07/%EC%95%88%EC%A0%84%ED%95%9C-jwt-%EC%9B%B9%EC%84%9C%EB%B9%84%EC%8A%A4-%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%9D%B8%EC%A6%9D-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0/)

**Comment by doorisopen** [comment]
Q1. 쿠키의 단점이 보안이 좋지 않다는 점인데, 이 단점을 헤더 설정 등으로 보완해서 전송한다면 어떨까?( @Kyejoon-Lee )

결론은 **쿠키 자체 설정으로 보완하는 방법은 없습니다.**

우선 쿠키의 보안적인 측면에서 나쁜 이유는 생각해보면 다음과 같습니다.

* 클라이언트 사이드에 정보를 저장
* 기본적으로 암호화를 제공하지 않음(그러나, 개발자가 직접 쿠키를 공개키를 사용해서하는 암호화? 하는 방법이 있는 것 같음)
* 쿠키는 기본적으로 공개되는 정보임

근데 쿠키 자체로 보안 설정을 하는 방법은 없고 쿠키는 공개되는 정보로 설계된 개념인듯합니다.

**클라이언트에 저장되는 모든 정보는 보안상 공개되어도 되는 정보**라고 보시면 될 듯 합니다.
